export const userActionTypes = {
    SET_CURRENT_USER: 'SET_CURRENT_USER',
    SET_USER_ACTIVE: 'SET_USER_ACTIVE',
    
    SET_USER_PHONE:'SET_USER_PHONE',
    SET_USER_PROFILE_DATA:'SET_USER_PROFILE_DATA',
    SET_USER_ID:'SET_USER_ID'
    
}